
resolution: 30
threshold: 0.8

Spirent:
        hub_host_mac_address : '00:10:11:08:11:01'
        hub_host_ip : ['None','None'] # None for auto detect IP
        hub_host_gateway : ['None','None']
        hub_host_prefix : ['None','None']
        hub_host_name : 'hub_host_vlan_99'
        hub_host_router :  ['']
        hub_host_vlan_id : 99
        udp_header : 33778
        remote_host_mac_address : '00:10:11:08:12:01'
        remote_host_ip : ['None','None'] # None for auto detect IP
        remote_host_gateway : ['None','None']
        remote_host_prefix : ['None','None']
        remote_host_name :  'remote_host_vlan_99'
        remote_host_router :  ['']
        remote_host_vlan_id : 99
        
        # Test configuration
        direction :  ['downstream','upstream']
        test_time :  '60'
        result_interval :  '10'
        mir_value : [1,1]  # given in Mbps, used to validate traffic flow
        udp_condition_list: ["RxStreamSummaryResults.FrameCount==TxStreamResults.FrameCount", "RxStreamSummaryResults.DroppedFramePercent<=0.00001"] #, "RxStreamSummaryResults.ReorderedFrameCount<=5"
        traffic : ['UDP','TCP','FTP']      # only for Simul Traffic
        
        # UDP traffic configuration
        str_fps :   [ 350, 350 ]
        str_frame_size :  [ 1500, 1500 ]
        packet_size : [1500, 1006, 494, 238, 110, 52]  # only for Imix
        int_weight : [10, 11, 15, 24, 20, 20]  # only for iMix
        frame_length_mode : 'IMIX'  # only for UDP -- it will ignored for other traffic type

        # TCP and FTP Configuration
        no_of_conn : ['200','200']
        file_size : ['1000000','1000000']
        ftp_no_of_conn : ['20','20']
        ftp_file_size : ['2000','2000']
RFC_Benchmark:
    trafficmode: MANUAL
    profileconfigmode: PER_SIDE
    frameiterationmode: CUSTOM
    customframesize: 256
    staggerdelay: 5
    delayaftertransmission: 5
    trafficstartdelay: 2
    latencytype: LILO
    enablelearning: FALSE
    enabledetailresult: TRUE
    enablejitter: TRUE
    enableexposedcommand: TRUE
    trials: 1
    durationmode: SECONDS
    durationseconds: 300
    backoffmode: FAILED_RATES
    loadspecmode: ['PER_STREAMBLOCK', 'PER_STREAMBLOCK']
    searchmode: ['COMBO', 'COMBO']
    ratelowerlimit: [1, 8.70]
    rateupperlimit: [150, 8.70]
    rateinitial: [20.5, 8.70]
    acceptedframeloss: [0.01, 0.01]
    enableoutofseq: [FALSE,FALSE]
    outofseqvalue: [100,50]
    loadunit: ['MEGABITS_PER_SECOND', 'MEGABITS_PER_SECOND']
    step: [2, 1]
    resolution: [0.1, 0.5]
    backoff: [50, 50]        
