name: Latest portfolio
on:
  schedule:
    - cron: '0 0 * * *'
    # This makes the action run at the end of every day. Customize this accordingly or you can also trigger this action for GitHub events (Pull, Push). Check the GitHub actions page for that.
  workflow_dispatch:

jobs:
  updating-portfolio:
    name: update-index-with-project
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Decode the GitHub App Private Key
        id: decode
        run: |
          private_key=$(echo "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAtb+43H53Gy/ohsPbYD+ICnAZAI8mWQ0yA8DzlNrtfCXdGjSq\ngmRSGWO4uqDOk7pHkyamvdczb1vtLo6nlLUxx68DLKfnKyRmKQ/2fwO3t9wlmrfJ\n8c4itlpf1GDYQeuZHdWNAJIyi24C4ZHYyNqE9nPQvmDU0V0gupgW2CF9Q+EdBqam\nZBRhiMDCYC0tZSHEC7ILyZA1Z2VcfW9GG7rYd7wAH+jjZEekbsB88O/TNielm5hT\nY8lOcwpPJDwA2DqDg3fb4FgujD6nFnNfO9HPSkJ6uUW88pj9fuqsasVkEPYzfXAj\nUl2qyWegGyVLLXyOQfIxyX3Lq1SASG6z68HReQIDAQABAoIBAGddz+yPfHwY5j1n\nPOhjmaKeGIop4Bx7lbtuzNoXHUQjYLmbxHH+TnckMRbriDGam0SEkgacUyN9e8qj\n1YmM9+/iiIKoR6BQxk2KR537ZkyKR1TUPGVq4HEnuyLVpYjwTpgaMWRmwZptCfRy\nd4HcTgzA17K+7arZNVkKUMvBWDX25txvjWmavonLUGDgLWddEpnxeiHeRUTfOzC9\npVOU0oGWaWeuq4jyG5OIWGh5fyoOmFZIvZSZribmRVRdkiw29MFu/O1W05KqLSXc\n2JrJt80NPPcx0Wi4FdluWURCJGL58pdP1faWMK2IZx7J+BOSmbMyQ67XBwm7uPhG\nEqOfMFUCgYEA6c67rj8zx3Kn+FJjQItsyO9Crz4N3zyHkHfS+ggwnaP2GlefSlk5\n25MdhVRVjjNYhEPPFOSWgUttAz0CjQY6Ds/cnEGlbouBLtHMGMvMjylRrPdyx8w9\nCNPLgMBxMnvQZDy+qrB6BzlO3R7HCDRz29g6fI7s09uRAsucQuvCcXcCgYEAxwAF\ncMidfAUztGkldNL8jhrnISAbjyxB2KHX9Eqw4HV+RMwHuRfRR1bP65fyVG0m2UZ4\ngkU1RM8tEV4gzHFWVimnFj5N3O21vos0PFnD42Uu6AEr3OT2mOCxVC8OCzyEgUha\n8ziCO0/NdCofsyChsShPw8goNuQi8LBK16CbEI8CgYEAk1DD5kVCTb/LX+YhTVDM\nCUrfnGUf/nE4BWnKT+oLH7hoXy6oWgMgNl5acmCxy3hEpInJF6PzxKGOnUS6r7ql\nqCGGIhomryFNEv/zdggq6mUhZjc/Ze4k4sP37DbU2/cxVYcEp62sJZMRQreatmu+\nOF3kdAjl5ZLpqnY6DdxYVn8CgYA7dPErMnWDQZaiN6w+TG+zEayvBAXX8DQ4Qprg\nXZSda91vNrqz/b7EntZ+oKaBvR8XWevVmFIDHhdsEgCgtNhD5CwNBE6FTOy5YqQX\nyAY0Id4y6W6ukCZxpOi2q1x51PoOGo06EE8w43YSWCeigIRvBwlWCK6jP+SEn1et\nN0o9VwKBgQCDmv8yzEBaWDYsgsk8j9o79PLkAXQubhcMRrxRoj/KGcbQT+3mavQb\nA0+2sxY5kI5t/C3UcS6leFOyFIzI00ffqjwFjv0ir1uujn1ylqookt2zXqvWCR0i\naX1UY1wA39DxdBlZNIZOiz3GZQduqJ35USM+W451xE0HwAYDSRiU3g==\n-----END RSA PRIVATE KEY-----" | base64 -d | awk 'BEGIN {ORS="\\n"} {print}' | head -c -2) &> /dev/null
          echo "::add-mask::$private_key"
          echo "private-key=$private_key" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: 1886822
          private-key: ${{ steps.decode.outputs.private-key }}
      - uses: actions/checkout@v2
      - uses: akarthik1709/PortfolioFy@main
        with:
          gh_token: ${{ steps.app-token.outputs.token }}
