name: Latest portfolio
on:
  schedule:
    - cron: '0 0 * * *'
    # This makes the action run at the end of every day. Customize this accordingly or you can also trigger this action for GitHub events (Pull, Push). Check the GitHub actions page for that.
  workflow_dispatch:

jobs:
  updating-portfolio:
    name: update-index-with-project
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Decode the GitHub App Private Key
        id: decode
        run: |
          private_key=$(echo "-----BEGIN RSA PRIVATE KEY----- 
MIIEpAIBAAKCAQEAtb+43H53Gy/ohsPbYD+ICnAZAI8mWQ0yA8DzlNrtfCXdGjSq 
gmRSGWO4uqDOk7pHkyamvdczb1vtLo6nlLUxx68DLKfnKyRmKQ/2fwO3t9wlmrfJ 
8c4itlpf1GDYQeuZHdWNAJIyi24C4ZHYyNqE9nPQvmDU0V0gupgW2CF9Q+EdBqam 
ZBRhiMDCYC0tZSHEC7ILyZA1Z2VcfW9GG7rYd7wAH+jjZEekbsB88O/TNielm5hT 
Y8lOcwpPJDwA2DqDg3fb4FgujD6nFnNfO9HPSkJ6uUW88pj9fuqsasVkEPYzfXAj 
Ul2qyWegGyVLLXyOQfIxyX3Lq1SASG6z68HReQIDAQABAoIBAGddz+yPfHwY5j1n  
POhjmaKeGIop4Bx7lbtuzNoXHUQjYLmbxHH+TnckMRbriDGam0SEkgacUyN9e8qj 
1YmM9+/iiIKoR6BQxk2KR537ZkyKR1TUPGVq4HEnuyLVpYjwTpgaMWRmwZptCfRy 
d4HcTgzA17K+7arZNVkKUMvBWDX25txvjWmavonLUGDgLWddEpnxeiHeRUTfOzC9 
pVOU0oGWaWeuq4jyG5OIWGh5fyoOmFZIvZSZribmRVRdkiw29MFu/O1W05KqLSXc 
2JrJt80NPPcx0Wi4FdluWURCJGL58pdP1faWMK2IZx7J+BOSmbMyQ67XBwm7uPhG
EqOfMFUCgYEA6c67rj8zx3Kn+FJjQItsyO9Crz4N3zyHkHfS+ggwnaP2GlefSlk5
25MdhVRVjjNYhEPPFOSWgUttAz0CjQY6Ds/cnEGlbouBLtHMGMvMjylRrPdyx8w9
CNPLgMBxMnvQZDy+qrB6BzlO3R7HCDRz29g6fI7s09uRAsucQuvCcXcCgYEAxwAF
cMidfAUztGkldNL8jhrnISAbjyxB2KHX9Eqw4HV+RMwHuRfRR1bP65fyVG0m2UZ4
gkU1RM8tEV4gzHFWVimnFj5N3O21vos0PFnD42Uu6AEr3OT2mOCxVC8OCzyEgUha
8ziCO0/NdCofsyChsShPw8goNuQi8LBK16CbEI8CgYEAk1DD5kVCTb/LX+YhTVDM
CUrfnGUf/nE4BWnKT+oLH7hoXy6oWgMgNl5acmCxy3hEpInJF6PzxKGOnUS6r7ql
qCGGIhomryFNEv/zdggq6mUhZjc/Ze4k4sP37DbU2/cxVYcEp62sJZMRQreatmu+
OF3kdAjl5ZLpqnY6DdxYVn8CgYA7dPErMnWDQZaiN6w+TG+zEayvBAXX8DQ4Qprg
XZSda91vNrqz/b7EntZ+oKaBvR8XWevVmFIDHhdsEgCgtNhD5CwNBE6FTOy5YqQX
yAY0Id4y6W6ukCZxpOi2q1x51PoOGo06EE8w43YSWCeigIRvBwlWCK6jP+SEn1et
N0o9VwKBgQCDmv8yzEBaWDYsgsk8j9o79PLkAXQubhcMRrxRoj/KGcbQT+3mavQb
A0+2sxY5kI5t/C3UcS6leFOyFIzI00ffqjwFjv0ir1uujn1ylqookt2zXqvWCR0i
aX1UY1wA39DxdBlZNIZOiz3GZQduqJ35USM+W451xE0HwAYDSRiU3g==
-----END RSA PRIVATE KEY-----" | base64 -d | awk 'BEGIN {ORS="\\n"} {print}' | head -c -2) &> /dev/null
          echo "::add-mask::$private_key"
          echo "private-key=$private_key" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: 1886822
          private-key: ${{ steps.decode.outputs.private-key }}
      - uses: actions/checkout@v2
      - uses: akarthik1709/PortfolioFy@main
        with:
          gh_token: ${{ steps.app-token.outputs.token }}
