name: Latest portfolio
on:
  schedule:
    - cron: '0 0 * * *'
    # This makes the action run at the end of every day. Customize this accordingly or you can also trigger this action for GitHub events (Pull, Push). Check the GitHub actions page for that.
  workflow_dispatch:

jobs:
  updating-portfolio:
    name: update-index-with-project
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      #- name: Generate a token
      #  id: generate_token
      #  uses: actions/create-github-app-token@v1
      #  with:
      #    #app_id: ${{ secrets.APP_ID }}
      #    #private_key: ${{ secrets.APP_PEM }}
      #    # Set the owner, so the token can be used in all repositories
      #    owner: ${{ github.repository_owner }}
      - uses: actions/checkout@v2
      - uses: akarthik1709/PortfolioFy@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
